## INDEXING AND SELECTION

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[6]

6

## BROADCASTING

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [5]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [7]:
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [8]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [9]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2-D ARRAY

In [10]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
arr_2d[1][2]

30

In [12]:
arr_2d[0:1]

array([[ 5, 10, 15]])

In [13]:
arr_2d[:1,2:]

array([[15]])

In [14]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:
bool_arr = arr>4

In [17]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])